<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="6" failed="6" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[created Pet With Empty Object]]>
    </line>
    <line>
      <![CDATA[update pet success]]>
    </line>
  </reporter-output>
  <suite started-at="2023-01-11T12:10:52 IST" name="testngpackage" finished-at="2023-01-11T12:10:56 IST" duration-ms="4799">
    <groups>
    </groups>
    <test started-at="2023-01-11T12:10:52 IST" name="sanity" finished-at="2023-01-11T12:10:56 IST" duration-ms="4799">
      <class name="app.petstore.api.UpdatePetTests">
        <test-method signature="updatePet()[pri:0, instance:app.petstore.api.UpdatePetTests@5149f008]" started-at="2023-01-11T12:10:54 IST" name="updatePet" finished-at="2023-01-11T12:10:55 IST" duration-ms="1211" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[update pet success]]>
            </line>
          </reporter-output>
        </test-method> <!-- updatePet -->
        <test-method signature="uploadPetImageByID()[pri:0, instance:app.petstore.api.UpdatePetTests@5149f008]" started-at="2023-01-11T12:10:54 IST" name="uploadPetImageByID" finished-at="2023-01-11T12:10:54 IST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadPetImageByID -->
      </class> <!-- app.petstore.api.UpdatePetTests -->
      <class name="app.petstore.api.StoreTests">
        <test-method signature="getInventory()[pri:0, instance:app.petstore.api.StoreTests@158d255c]" started-at="2023-01-11T12:10:54 IST" name="getInventory" finished-at="2023-01-11T12:10:55 IST" duration-ms="598" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4] but found [5]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at app.petstore.api.StoreTests.getInventory(StoreTests.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getInventory -->
      </class> <!-- app.petstore.api.StoreTests -->
      <class name="app.petstore.api.UserTests">
        <test-method signature="createUser()[pri:0, instance:app.petstore.api.UserTests@7072bc39]" started-at="2023-01-11T12:10:54 IST" name="createUser" finished-at="2023-01-11T12:10:56 IST" duration-ms="2469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
      </class> <!-- app.petstore.api.UserTests -->
      <class name="app.absproj.api.NegativeEmailTests">
        <test-method is-config="true" signature="before_test()[pri:0, instance:app.absproj.api.NegativeEmailTests@2a492f2a]" started-at="2023-01-11T12:10:52 IST" name="before_test" finished-at="2023-01-11T12:10:53 IST" duration-ms="1010" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_test -->
        <test-method is-config="true" signature="before_test()[pri:0, instance:app.absproj.api.NegativeEmailTests@2a492f2a]" started-at="2023-01-11T12:10:52 IST" name="before_test" finished-at="2023-01-11T12:10:53 IST" duration-ms="1010" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_test -->
        <test-method is-config="true" signature="before_test()[pri:0, instance:app.absproj.api.NegativeEmailTests@2a492f2a]" started-at="2023-01-11T12:10:52 IST" name="before_test" finished-at="2023-01-11T12:10:53 IST" duration-ms="1010" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_test -->
        <test-method signature="emptyEmailTest()[pri:0, instance:app.absproj.api.NegativeEmailTests@2a492f2a]" started-at="2023-01-11T12:10:53 IST" name="emptyEmailTest" finished-at="2023-01-11T12:10:53 IST" duration-ms="665" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [429]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at app.absproj.api.NegativeEmailTests.emptyEmailTest(NegativeEmailTests.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyEmailTest -->
        <test-method signature="invalidApiKeyTest()[pri:0, instance:app.absproj.api.NegativeEmailTests@2a492f2a]" started-at="2023-01-11T12:10:53 IST" name="invalidApiKeyTest" finished-at="2023-01-11T12:10:53 IST" duration-ms="694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidApiKeyTest -->
        <test-method signature="invalidEmailTest()[pri:0, instance:app.absproj.api.NegativeEmailTests@2a492f2a]" started-at="2023-01-11T12:10:53 IST" name="invalidEmailTest" finished-at="2023-01-11T12:10:53 IST" duration-ms="661" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at app.absproj.api.NegativeEmailTests.invalidEmailTest(NegativeEmailTests.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidEmailTest -->
      </class> <!-- app.absproj.api.NegativeEmailTests -->
      <class name="app.petstore.api.CreatePetTests">
        <test-method signature="createPetWithDuplicateID()[pri:0, instance:app.petstore.api.CreatePetTests@525d79f0]" started-at="2023-01-11T12:10:52 IST" name="createPetWithDuplicateID" finished-at="2023-01-11T12:10:54 IST" duration-ms="2162" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [409] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [409] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at app.petstore.api.CreatePetTests.createPetWithDuplicateID(CreatePetTests.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPetWithDuplicateID -->
        <test-method signature="createPet()[pri:0, instance:app.petstore.api.CreatePetTests@525d79f0]" started-at="2023-01-11T12:10:52 IST" name="createPet" finished-at="2023-01-11T12:10:54 IST" duration-ms="2168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPet -->
        <test-method signature="createPetWithUnsupportedMediaType()[pri:0, instance:app.petstore.api.CreatePetTests@525d79f0]" started-at="2023-01-11T12:10:53 IST" name="createPetWithUnsupportedMediaType" finished-at="2023-01-11T12:10:54 IST" duration-ms="589" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[created Pet With Empty Object]]>
            </line>
          </reporter-output>
        </test-method> <!-- createPetWithUnsupportedMediaType -->
        <test-method signature="createPetWithEmptyObject()[pri:0, instance:app.petstore.api.CreatePetTests@525d79f0]" started-at="2023-01-11T12:10:53 IST" name="createPetWithEmptyObject" finished-at="2023-01-11T12:10:54 IST" duration-ms="613" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at app.petstore.api.CreatePetTests.createPetWithEmptyObject(CreatePetTests.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPetWithEmptyObject -->
        <test-method signature="createPetWithoutID()[pri:0, instance:app.petstore.api.CreatePetTests@525d79f0]" started-at="2023-01-11T12:10:53 IST" name="createPetWithoutID" finished-at="2023-01-11T12:10:54 IST" duration-ms="631" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at app.petstore.api.CreatePetTests.createPetWithoutID(CreatePetTests.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPetWithoutID -->
      </class> <!-- app.petstore.api.CreatePetTests -->
    </test> <!-- sanity -->
  </suite> <!-- testngpackage -->
</testng-results>
